In [5]:
# 1. Import the numpy package under the name np (★☆☆)
import numpy as np

In [6]:
# 2. Print the numpy version
print(np.version.version)

1.21.5


In [7]:
# 3. Create a null vector of size 10 (★☆☆)
np_array=np.zeros(10)
np_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# 4. Given a numpy array whose underlying data is of 'int32' type. Change the dtype of the given object to 'float64'
np_array.astype('float64')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
#Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
np_arr=np.zeros(10)
np_arr[4]=1
np_arr


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [11]:
# # 4. Numpy where Problem
# Say we have a numpy array A
# 
# [[1 2 3] [4 5 6]]
# 
# Create a new matrix with Indices of elements <4
# 
# Output Elements which are <4 array([1, 2, 3])  ***
np_ar=np.array([[1,2,3],[4,5,6]])
print(np_ar[(np_ar<4)])

[1 2 3]


In [12]:
# 5. Create a vector with values ranging from 10 to 49 (★☆☆)

array_1 = np.arange(10, 50)
print(array_1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
# 6. Reverse a vector (first element becomes last) (★☆☆)
rev_array_1 = array_1[::-1]
rev_array_1

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [14]:
# 7. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
array_2=np.arange(0,9)
array_2=array_2.reshape(3,3)
array_2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:

# 8. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
array_3=np.array([1,2,0,0,4,0])
print(np.nonzero(array_3))

(array([0, 1, 4], dtype=int64),)


In [16]:
array_4=np.array([1,2,0,0,4,0])
array_4= np.where(array_4 != 0)[0]
print(array_4)

[0 1 4]


In [17]:

# 9. Create a 3x3 identity matrix (★☆☆)


identity_array = np.identity(3, dtype=int)
print(identity_array)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [25]:
# Create a 3x3x3 array with random values (★☆☆)
import random
dim_3 = np.random.randint(1,50,(3,3,3))
print(dim_3)

[[[29 22 45]
  [38 11 46]
  [23  3 33]]

 [[ 1 25 31]
  [48 39 29]
  [46  1 24]]

 [[ 3 19 35]
  [35 12 20]
  [ 7  4  3]]]


In [26]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
dim_10_10= np.random.randint(1,50,(10,10))
print(dim_10_10)
print("\nMinimum Values\nColumnwise(Axis=0): ",np.min(dim_10_10, axis=0))
print("Row-wise(Axis=1): ",np.min(dim_10_10, axis=1))
print("Among Total-values(Axis=None): ",np.min(dim_10_10, axis=None))
print("\nMaximum Values\nColumnwise(Axis=0): ",np.max(dim_10_10, axis=0))
print("Row-wise(Axis=1): ",np.max(dim_10_10, axis=1))
print("Among Total-values(Axis=None): ",np.max(dim_10_10, axis=None))

[[24  5  5 48 22 29 38 15 18  2]
 [13  5 34 48 34 37 11 29  5 29]
 [42 17 37 30 29 43  9  8 41 36]
 [36 48  6 31 42 41  8  9 15  2]
 [ 7 32 12 18 10 30 31 47 39 26]
 [ 8 38  7 49 30 28 14 21 12 16]
 [10  2 14 40 19 48 40 49 38 19]
 [38 41 26 25 10 29 32 23 43  4]
 [41 10 28 33 30  7 41 16 26 39]
 [39 10 42  8 47  1  2  2 37 17]]

Minimum Values
Columnwise(Axis=0):  [ 7  2  5  8 10  1  2  2  5  2]
Row-wise(Axis=1):  [2 5 8 2 7 7 2 4 7 1]
Among Total-values(Axis=None):  1

Maximum Values
Columnwise(Axis=0):  [42 48 42 49 47 48 41 49 43 39]
Row-wise(Axis=1):  [48 48 43 48 47 49 49 43 41 47]
Among Total-values(Axis=None):  49


In [27]:
# 14. Create a random vector of size 30 and find the mean value (★☆☆)
dim_30= np.random.randint(1,50,(30))
print(dim_30)
print("Mean: ",np.mean(dim_30, axis=None))

[36 35 37  6 16 27 24 44 27 21 26  3  2 43  5 23 14 30 34 22 28 24  1 27
 36  3 22 19 44 15]
Mean:  23.133333333333333


In [29]:
# 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
n = 5
m = 4
print("USING pad()")
zero_arr = np.zeros((n, m), int)
bordered_2d = np.pad(zero_arr, pad_width=1, mode='constant', constant_values=1)
print(bordered_2d)

USING pad()
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [30]:
# 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
np_array = [[1, 2],[3, 4]] 
bordered = np.pad(np_array, pad_width=1, mode='constant', constant_values=0)
print(bordered)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


In [31]:
# 17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [32]:
print("0 * np.nan : ",0 * np.nan)
print("np.nan == np.nan : ",np.nan == np.nan) 
print("np.inf > np.nan : ",np.inf > np.nan)
print("np.nan - np.nan :", np.nan - np.nan)
print("np.nan in set([np.nan]) :", np.nan in set([np.nan]))
print("0.3 == 3 * 0.1 :", 0.3 == 3 * 0.1) # [3*0.1=0.30000000000000004]

0 * np.nan :  nan
np.nan == np.nan :  False
np.inf > np.nan :  False
np.nan - np.nan : nan
np.nan in set([np.nan]) : True
0.3 == 3 * 0.1 : False


In [33]:
# 18. Create a 4x4 matrix with values 0,1,2,3 just below the diagonal (★☆☆)
np.diag(np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0]])

In [35]:
# 19. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
null_vector = np.zeros((10),dtype=int)
null_vector[4] = 1
print(null_vector)

[0 0 0 0 1 0 0 0 0 0]


In [36]:
# 22. Normalize a 5x5 random matrix (★☆☆) 
#Say X is 5*5 numpy array Normalize i.e X - mean(X) / Standard Deviation of X link text

import numpy as np
a_55 = np.random.randint(1,50,(5,5))
a_55_norm = (a_55 - np.mean(a_55)) / np.std(a_55)
print(a_55)
print(a_55_norm)

[[16 17 39 36 19]
 [ 8 43 27 28  2]
 [12  6 15 24 29]
 [ 5 39 47 38 46]
 [ 7 27 25  3 21]]
[[-0.52035323 -0.4476782   1.15117252  0.93314742 -0.30232814]
 [-1.1017535   1.44187265  0.27907213  0.35174716 -1.53780369]
 [-0.81105337 -1.24710356 -0.59302827  0.06104703  0.42442219]
 [-1.31977859  1.15117252  1.73257278  1.07849749  1.65989775]
 [-1.17442853  0.27907213  0.13372206 -1.46512866 -0.15697807]]


23. Numpy where Problem
Say we have a numpy array A

[[1 2 3] [4 5 6]]

Create a new matrix with Indices of elements <4

Output Elements which are <4 array([1, 2, 3])

In [37]:
array_6 = np.array([[1,2,3],[4,5,6]])
print(array_6[array_6<4])

[1 2 3]


In [39]:
# 24. Do a dot product of 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
array_53 = np.random.randint(1,20,(5,3))
array_32 = np.random.randint(1,20,(3,2))
print(array_53)
print(array_32)
print(np.dot(array_53, array_32))

[[ 2 16 11]
 [18  8  7]
 [16  9 17]
 [ 2  2 18]
 [12 12  7]]
[[12 13]
 [ 7 19]
 [ 2 13]]
[[158 473]
 [286 477]
 [289 600]
 [ 74 298]
 [242 475]]


In [40]:
# 25. Consider two random array A and B, check if they are equal (★★☆)
A = np.random.randint(1,5,(3,3))
B = np.random.randint(1,5,(3,3))
print(A)
print(B)
print(np.array_equal(A, B))
print(A == B) 
print(np.allclose(A, B))
A1 = [[1,2,3],[4,5],[6,7,8],[9]]
B1 = [[1,2,3],[4,5],[6,7,8],[10]]
print(np.array_equal(A1, B1))
print(A1 == B1)

[[3 4 1]
 [2 1 1]
 [1 3 2]]
[[4 3 3]
 [3 1 2]
 [4 1 1]]
False
[[False False False]
 [False  True False]
 [False False False]]
False
False
False


C:\Users\hemachandrao.balu\Anaconda3\lib\site-packages\numpy\core\numeric.py:2440: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a1, a2 = asarray(a1), asarray(a2)


In [43]:
# 26. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
A1 = np.random.randint(1,10,(10))
temp = A1
print(A1)
max_value = np.max(A1)
print(max_value)
A1[A1 == max_value] = 0
print(A1)


[4 2 3 8 8 6 2 8 3 6]
8
[4 2 3 0 0 6 2 0 3 6]


In [49]:
# 27. Subtract the mean of each row of a matrix (★★☆):
print(array_53)
Array53_mean=np.mean(array_53, axis=0)
print(Array53_mean)

[[ 2 16 11]
 [18  8  7]
 [16  9 17]
 [ 2  2 18]
 [12 12  7]]
[10.   9.4 12. ]
